### ISSUE TITLE
a lot of executions of the script html / wp-content / plugins / rcp-file-protector-master / file-guard.php 

### ISSUE THREAD

**Issue by bastinahrungsglueck** [angay9/rcp-file-protector#20]
Hi Andriy,

I need your help. I installed your plugin on www.nahrungsglueck.de, but I don't use it now. The plugin is deactivated because I have some troubleshooting with the plugin mailchimp for WooCommerce. After the installation all my picture were not shown and front and backend (error screen are attached)
![Bildschirmfoto 2021-10-12 um 18 14 18](https://user-images.githubusercontent.com/95097545/143614057-59b9d717-5760-4d13-8ffe-f7e50a76df7f.png)
. I want to delete your plugin from our site, but the whole site crashed down. It means at the moment I can't delete it. 

Today I have a new problem with your plugin. It is not active and my hoster writes me the following: Yesterday morning there were a lot of executions of the script html / wp-content / plugins / rcp-file-protector-master / file-guard.php through HTTP calls such as https://nahrungsglueck.de/wp-content/uploads/et -fonts / AmaticSC-Bold.ttf which meant that a process limit took effect on our server and the content could not be delivered.

Can you help me please? How can I delete the plugin or stop running plugin php.

Thank you, Sebastian

**Comment by angay9** [comment]
Hi Sebastian.

Can you check your .htacccess file and remove the code starting from "# RCP File Protector Rules" and ending with "# End RCP File Protector Rules".

Thanks

**Comment by bastinahrungsglueck** [comment]
Hi Andriy. Thank you for your help. No it works. Best, Sebastian
